[tasks.generate-bindings]
command = "cargo"
args = ["test"]
env = { "TS_RS_EXPORT_DIR" = "webui/src/bindings" }

[tasks.build-backend]
command = "cargo"
args = ["build"]

[tasks.build-frontend]
command = "npm"
args = ["run", "build"]
cwd = "webui"

[tasks.run]
command = "cargo"
args = ["shuttle", "run"]

[tasks.generate-changelog]
command = "git"
args = ["cliff", "-o", "webui/public/CHANGELOG.md"]

[tasks.generate-version]
script = "git describe > webui/public/version.txt"


[tasks.workflow]
dependencies = [
    "generate-bindings",
    "generate-changelog",
    "generate-version",
    "build-frontend",
    "build-backend",
    "run",
]
