// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateItem = { name: string, inspection_period_days: number | null, serial_number: string | null, tags: Array<bigint>, };
