// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTag = { 
/**
 * Name of the tag to create
 */
name: string, 
/**
 * Color of the tag
 */
color: string, };
