// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemEvent = { 
/**
 * Id of the event
 */
id: bigint, 
/**
 * Timestamp of the event
 */
ts: string, };
