// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tag = { 
/**
 * Id of the tag
 */
id: bigint, 
/**
 * Name of the tag
 */
name: string, 
/**
 * Color of the tag
 */
color: string, };
