name: SafeGear CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  TS_RS_EXPORT_DIR: target/bindings

jobs:
  # Run tests, generate Typescript bindings
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Generate Cargo.lock
      run: cargo generate-lockfile
    - name: Restore Rust cache
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Cargo test
      run: cargo test --release --verbose
    - name: Upload TypeScript bindings
      uses: actions/upload-artifact@v4
      with:
        name: ts-bindings
        path: target/bindings
    - name: Save Rust cache
      uses: actions/cache/save@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}


  frontend-build:
    runs-on: ubuntu-latest
    needs: [backend-test]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download TypeScript bindings
      uses: actions/download-artifact@v4
      with:
        name: ts-bindings
        path: webui/src/bindings
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: webui/package-lock.json
    - run: npm ci
      working-directory: webui
    - run: npm run build --if-present
      working-directory: webui
    - name: Upload WebUI
      uses: actions/upload-artifact@v4
      with:
        name: webui-dist
        path: webui/dist

  backend-build:
    runs-on: ubuntu-latest
    needs: [frontend-build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Generate Cargo.lock
      run: cargo generate-lockfile
    - name: Restore Rust cache
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Download WebUI
      uses: actions/download-artifact@v4
      with:
        name: webui-dist
        path: webui/dist
    - name: Build release
      run: cargo build --release
    - name: Save Rust cache
      uses: actions/cache/save@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Upload release bin
      uses: actions/upload-artifact@v4
      with:
        name: target-release-bin
        path: target/release/safegear

  deploy:
    runs-on: ubuntu-latest
    needs: [frontend-build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Generate Cargo.lock
      run: cargo generate-lockfile
    - name: Restore Rust cache
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Download WebUI
      uses: actions/download-artifact@v4
      with:
        name: webui-dist
        path: webui/dist/
    - uses: shuttle-hq/deploy-action@main
      with:
        deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
        allow-dirty: "true"
        no-test: "true"
    - name: Save Rust cache
      uses: actions/cache/save@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
