name: SafeGear CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  TS_RS_EXPORT_DIR: target/bindings

jobs:
  # Run tests, generate Typescript bindings
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Cargo test
      run: cargo test --verbose
    - name: Upload TypeScript bindings
      uses: actions/upload-artifact@v4
      with:
        name: ts-bindings
        path: target/bindings


  frontend-build:
    runs-on: ubuntu-latest
    needs: [backend-test]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download TypeScript bindings
      uses: actions/download-artifact@v4
      with:
        name: ts-bindings
        path: webui/src/bindings
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: webui/package-lock.json
    - run: npm ci
      working-directory: webui
    - run: npm run build --if-present
      working-directory: webui
    - name: Upload WebUI
      uses: actions/upload-artifact@v4
      with:
        name: webui-dist
        path: webui/dist

  backend-build:
    runs-on: ubuntu-latest
    needs: [frontend-build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download WebUI
      uses: actions/download-artifact@v4
      with:
        name: webui-dist
        path: webui/dist
    - name: Build debug
      run: cargo build
    - name: Build release
      run: cargo build --release
    - name: Upload release bin
      uses: actions/upload-artifact@v4
      with:
        name: target-release-bin
        path: target/release/safegear
